server:
  port: 8080
  servlet:
    context-path: /storage
spring:
  application:
    name: storage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storage
    username: root
    password: root